# Analyzing California's Bridges (National Bridge Inventory Database, 2019):

The dataset used for this analysis is obtained from the Federal Highway Administration (FHWA). FHWA website consists of databases from all states' Departments of Transportation (DOT) nationwide. This specific analysis has been conducted on California's bridge inventory dataset (25,772 bridges as of 2019). 

The dataset is not a csv formatted version. It is imported and converted to a csv format without headings. Initially, throughout this analysis, it is expected to clean, wrangle, and organize the dataset prior to analysis. 

Recording and Coding Guide for the Structure Inventory and Appraisal of the Nation's Bridges:
https://www.fhwa.dot.gov/bridge/mtguide.pdf

Link to the FHWA CA 2019 Bridge Inventory Dataset:

Disclaimer:
https://www.fhwa.dot.gov/bridge/nbi/disclaim.cfm?nbiYear=2019&nbiState=CA19

Dataset:
https://www.fhwa.dot.gov/bridge/nbi/2019/CA19.txt

## 1.0 Importing Python Necessary Modules and Dataset:

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
filename = 'CA2019.csv'
df = pd.read_csv(filename)

In [3]:
df

                                                 Column1
0      069        06 00211110000500008900000Shasta La...
1      069        19P00051700000000006100000N. Fork A...
2      069        1CA00701660000000711158296MUGU LAGO...
3      069        1CA00951800000001107366000BOONE DRI...
4      069        1CA01411660000000711158296DISTRICT ...
...                                                  ...
25766  069DAPFORNTC0000141800000000807125114STORM DRA...
25767  069DAPFORNTC0000151800000000807125114STORM DRA...
25768  069JPLFACILITY02851580000000703756000ARROYO SE...
25769  069M6--14.508     16000M0600003300000STREAM   ...
25770  069M6--15.806     16000M0600003300000STREAM   ...

[25771 rows x 1 columns]

## 2.0 Data Cleaning and Wrangling:

### 2.1 Introducing +50 Header Titles for the Dataset per Coding Guidelines of Nation's Bridges:

In [4]:
df['State ID'] = df['Column1'].str[0:3]
df['Structure #'] = df['Column1'].str[3:18]
df['Inventory Route'] = df['Column1'].str[18:27]
df['HwyAgency District'] = df['Column1'].str[27:29]
df['County Code'] = df['Column1'].str[29:32]
df['Place Code'] = df['Column1'].str[32:37]
df['Feature Int'] = df['Column1'].str[37:62]
df['Facility Carried by Str.'] = df['Column1'].str[62:80]
df['Location'] = df['Column1'].str[80:105]
df['Min. Vert. Clearance'] = df['Column1'].str[105:109]
df['KM Point'] = df['Column1'].str[109:116]
df['Base HWY Ntwrk'] = df['Column1'].str[116:117]
df['SubRte #'] = df['Column1'].str[117:129]
df['Lat (DD-MM-SS.ss)'] = df['Column1'].str[129:137]
df['Long (DDD-MM-SS.ss)'] = df['Column1'].str[137:146]
df['DTR Len'] = df['Column1'].str[146:149]
df['Toll'] = df['Column1'].str[149:150]
df['Maint. Resp.'] = df['Column1'].str[150:152]
df['Owner'] = df['Column1'].str[152:154]

df['Func Class'] = df['Column1'].str[154:156]
#Functional Classifications:
 #   Rural:
 #01 Principal Arterial - Interstate
 #02 Principal Arterial - Other
 #06 Minor Arterial
 #07 Major Collector
 #08 Minor Collector
 #09 Local
 #   Urban:
 #11 Principal Arterial - Interstate
 #12 Principal Arterial - Other Freeways or
 #   Expressways:
 #14 Other Principal Arterial
 #16 Minor Arterial
 #17 Collector
 #19 Local

df['Year Built'] = df['Column1'].str[156:160]
df['Lanes On Str.'] = df['Column1'].str[160:162]
df['Lanes Under Str.'] = df['Column1'].str[162:164]
df['ADT'] = df['Column1'].str[164:170]
df['Year of ADT'] = df['Column1'].str[170:174]

df['Design Load'] = df['Column1'].str[174:175] 
# (code/metric load/English load) = (1/M9/H10, 2/M13.5/H15, 3/M13.5/HS15, 4/M18/H20, 5/MS18/HS20, 6/MS18mod/HS20mod, 7/Pedest./Pedest., 8/Railroad/Railroad, 9/MS22.5/HS25, 0/Unknown)

df['App. Rdwy Width'] = df['Column1'].str[175:179]
#unit in meters (xxx.x) 4 digits

df['Br. Median'] = df['Column1'].str[179:180]
df['Skew'] = df['Column1'].str[180:182] #skew (xx degrees)
df['Flared'] = df['Column1'].str[182:183] #binary 0=no, 1=yes
df['Tr Sfty Feat'] = df['Column1'].str[183:187] #consists of "Bridge Railings-184", "Transitions-185", "Approach Guard Rail-186", "Approach Gurdrail Ends-187"

df['Hist. Value'] = df['Column1'].str[187:188]
#Code  Description
# 1    Bridge is on the National Register of Historic Places.
# 2    Bridge is eligible for the National Register of Historic Places.
# 3    Bridge is possibly eligible for the National Register of Historic Places (requires further investigation before determination can be made) or bridge is on a State or local historic register.
# 4    Historical significance is not determinable at this time.
# 5    Bridge is not eligible for the National Register of Historic Places.

df['Navi Ctrl'] = df['Column1'].str[188:189]
#Indicate for this item whether or not navigation control (a bridge permit for navigation) is required. Use one of the following codes:
# Code Description
# N Not applicable, no waterway.
# 0 No navigation control on waterway (bridge permit not required).
# 1 Navigation control on waterway (bridge permit required).

df['Navi Ver Clr'] = df['Column1'].str[189:193] # xxx.x meters
df['Navi Hor Clr'] = df['Column1'].str[193:198] # xxxx.x meters
df['Str Opn/ Pstd/ Clsd'] = df['Column1'].str[198:199] # Operation status of the bridge
df['Type of Srvc'] = df['Column1'].str[199:201] 
df['Str Type'] = df['Column1'].str[201:204] # 3 digits (1st structure material, 2nd & 3rd Str. Type). Example: Cont. Conc. Multiple Box Grdr. = 205
df['Str Type App Spans'] = df['Column1'].str[204:207]
df['Span # in Main Unit'] = df['Column1'].str[207:210]
df['App Span #'] = df['Column1'].str[210:214]
df['Max Span Len'] = df['Column1'].str[217:222] # 5 digits (xxxx.x meters)
df['Str Len (m)'] = df['Column1'].str[222:228] # 6 digits (xxxxx.x meters)
df['Rdwy Width (m)'] = df['Column1'].str[234:238] # 4 digits (xxx.x meters)
df['Deck Width (m)'] = df['Column1'].str[238:242] # 4 digits (xxx.x meters)
df['Deck Cndtn Rtg'] = df['Column1'].str[258:259] #Condition rating from 0(failed)-9(Excellent)-N(Not Applicable)
df['Super Cndtn Rtg'] = df['Column1'].str[259:260]
df['Sub Cndtn Rtg'] = df['Column1'].str[260:261]
df['Channel Cndtn Rtg'] = df['Column1'].str[261:262]
df['Culvert Cndtn Rtg'] = df['Column1'].str[262:263]
df['Method Rtg'] = df['Column1'].str[263:264]
df['Operating Rtg'] = df['Column1'].str[264:267] # 3 digits (xx.x metric tons)
df['Invntry Rtg'] = df['Column1'].str[268:271]
df['Str Eval'] = df['Column1'].str[271:272]
df['Deck Geom'] = df['Column1'].str[272:273]
df['UndClr, Ver, Hor'] = df['Column1'].str[273:274]
df['Br Pstng'] = df['Column1'].str[274:275]
df['WatWy Adequcy'] = df['Column1'].str[275:276]
df['App Rdwy Align'] = df['Column1'].str[276:277]
df['Type of Work'] = df['Column1'].str[277:280]
df['Len Str Imprvmnt'] = df['Column1'].str[280:286] # 6 digits (xxxxx.x meters)
df['Inspection Date'] = df['Column1'].str[286:290] # 4 digits (1192 = Nov. 1992)
df['Insp Freq (mths)'] = df['Column1'].str[290:292]
df['Crtcl Feat Insp'] = df['Column1'].str[292:301]
df['Crtcl Feat Insp Date'] = df['Column1'].str[301:313]
df['Br Impvmt $'] = df['Column1'].str[313:319] # 6digits (eg. $55,850 = 000056 or $7,451,233 = 007451)
df['Rdwy Impvmt $'] = df['Column1'].str[319:325]
df['Total Proj $'] = df['Column1'].str[325:331]
df['Yr of Impvmt $ Estmt'] = df['Column1'].str[331:335] # year 4 digits (1995)
df['Yr Rcnstrctd'] = df['Column1'].str[361:365]
df['Deck Type'] = df['Column1'].str[365:366]
df['ADTT'] = df['Column1'].str[369:371]
df['NBIS Br Len'] = df['Column1'].str[373:374] #Y/N 1-char (is it eligible for min. leng of NBIS as a bridge? Y/N)
df['Scour Crtcl Br'] = df['Column1'].str[374:375] # 0(it is scour-crtical) to 9(well above flood line) to T(Tidal) to U(Unknown) to N(Not over waterway)
df['Future ADT'] = df['Column1'].str[375:381]
df['Yr of Future ADT'] = df['Column1'].str[381:385]

df['Bridge Cndn CAT10'] = df['Column1'].str[433:434]
df['Ovreall Bridge Cndn CAT23'] = df['Column1'].str[434:435]

del df["Column1"]

df.to_csv("new_data.csv", index=False)

df.tail(1000)

,State ID,Structure #,Inventory Route,HwyAgency District,County Code,Place Code,Feature Int,Facility Carried by Str.,Location,Min. Vert. Clearance,...,Yr of Impvmt $ Estmt,Yr Rcnstrctd,Deck Type,ADTT,NBIS Br Len,Scour Crtcl Br,Future ADT,Yr of Future ADT,Bridge Cndn CAT10,Ovreall Bridge Cndn CAT23
24771,069,58 0139,131001110,11,025,00000,"""X"" DRAIN",STATE ROUTE 111,11-IMP-111-40.82,9999,...,,1986,1,17,Y,5,005999,2037,G,7
24772,069,58 0142,131001110,11,025,00000,ALAMO RIVER,STATE ROUTE 111,11-IMP-111-29.51,9999,...,,0000,1,22,Y,5,019319,2037,G,7
24773,069,58 0143,131001110,11,025,00000,MARSHY WASH,STATE ROUTE 111,11-IMP-111-41.10,9999,...,,1986,1,05,Y,5,006050,2037,G,7
24774,069,58 0145,131001110,11,025,00000,KUEHN DRAW WASH,STATE ROUTE 111,11-IMP-111-42.24,9999,...,,1986,N,03,Y,8,006050,2037,G,7
24775,069,58 0146,131001110,11,025,00000,CHICO WASH,STATE ROUTE 111,11-IMP-111-42.35,9999,...,,1986,1,03,Y,5,006050,2037,G,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25766,069,DAPFORNTC000014,180000000,08,071,25114,STORM DRAINAGE,BARSTOW RD,0.2 MI. NE LOOP RD.,9999,...,2018,0000,N,12,Y,8,002967,2036,F,6
25767,069,DAPFORNTC000015,180000000,08,071,25114,STORM DRAINAGE CHANNEL,GOLDSTONE RD,NEAR RHINELAND DRIVE,9999,...,2018,0000,N,12,Y,8,001815,2036,F,6
25768,069,JPLFACILITY0285,158000000,07,037,56000,ARROYO SECO,EXPLORER ROAD,2.4 KM N. I-210/ARROYO,9999,...,2018,0000,1,05,Y,3,003000,2035,F,5
25769,069,M6--14.508,16000M060,00,033,00000,STREAM,ROAD,EEL RIVER,9999,...,,0000,N,00,Y,2,000075,2039,F,5
25770,069,M6--15.806,16000M060,00,033,00000,STREAM,ROAD,TROUT CREEK,9999,...,,0000,N,00,Y,2,000075,2039,F,5

### 2.2 Identifying and Counting Missing Data:

In [5]:
missing_null = df.isnull()
missing_null.tail()

for column in missing_null.columns.values.tolist():
    print(column)
    print (missing_null[column].value_counts())
    print("")

State ID
False    25771
Name: State ID, dtype: int64

Structure #
False    25771
Name: Structure #, dtype: int64

Inventory Route
False    25771
Name: Inventory Route, dtype: int64

HwyAgency District
False    25771
Name: HwyAgency District, dtype: int64

County Code
False    25771
Name: County Code, dtype: int64

Place Code
False    25771
Name: Place Code, dtype: int64

Feature Int
False    25771
Name: Feature Int, dtype: int64

Facility Carried by Str.
False    25771
Name: Facility Carried by Str., dtype: int64

Location
False    25771
Name: Location, dtype: int64

Min. Vert. Clearance
False    25771
Name: Min. Vert. Clearance, dtype: int64

KM Point
False    25771
Name: KM Point, dtype: int64

Base HWY Ntwrk
False    25771
Name: Base HWY Ntwrk, dtype: int64

SubRte #
False    25771
Name: SubRte #, dtype: int64

Lat (DD-MM-SS.ss)
False    25771
Name: Lat (DD-MM-SS.ss), dtype: int64

Long (DDD-MM-SS.ss)
False    25771
Name: Long (DDD-MM-SS.ss), dtype: int64

DTR Len
False    25771
Name: DTR Len, dtype: int64

Toll
False    25771
Name: Toll, dtype: int64

Maint. Resp.
False    25771
Name: Maint. Resp., dtype: int64

Owner
False    25771
Name: Owner, dtype: int64

Func Class
False    25771
Name: Func Class, dtype: int64

Year Built
False    25771
Name: Year Built, dtype: int64

Lanes On Str.
False    25771
Name: Lanes On Str., dtype: int64

Lanes Under Str.
False    25771
Name: Lanes Under Str., dtype: int64

ADT
False    25771
Name: ADT, dtype: int64

Year of ADT
False    25771
Name: Year of ADT, dtype: int64

Design Load
False    25771
Name: Design Load, dtype: int64

App. Rdwy Width
False    25771
Name: App. Rdwy Width, dtype: int64

Br. Median
False    25771
Name: Br. Median, dtype: int64

Skew
False    25771
Name: Skew, dtype: int64

Flared
False    25771
Name: Flared, dtype: int64

Tr Sfty Feat
False    25771
Name: Tr Sfty Feat, dtype: int64

Hist. Value
False    25771
Name: Hist. Value, dtype: int64

Navi Ctrl
False    25771
Name: Navi Ctrl, dtype: int64

Navi Ver Clr
False    25771
Name: Navi Ver Clr, dtype: int64

Navi Hor Clr
False    25771
Name: Navi Hor Clr, dtype: int64

Str Opn/ Pstd/ Clsd
False    25771
Name: Str Opn/ Pstd/ Clsd, dtype: int64

Type of Srvc
False    25771
Name: Type of Srvc, dtype: int64

Str Type
False    25771
Name: Str Type, dtype: int64

Str Type App Spans
False    25771
Name: Str Type App Spans, dtype: int64

Span # in Main Unit
False    25771
Name: Span # in Main Unit, dtype: int64

App Span #
False    25771
Name: App Span #, dtype: int64

Max Span Len
False    25771
Name: Max Span Len, dtype: int64

Str Len (m)
False    25771
Name: Str Len (m), dtype: int64

Rdwy Width (m)
False    25771
Name: Rdwy Width (m), dtype: int64

Deck Width (m)
False    25771
Name: Deck Width (m), dtype: int64

Deck Cndtn Rtg
False    25771
Name: Deck Cndtn Rtg, dtype: int64

Super Cndtn Rtg
False    25771
Name: Super Cndtn Rtg, dtype: int64

Sub Cndtn Rtg
False    25771
Name: Sub Cndtn Rtg, dtype: int64

Channel Cndtn Rtg
False    25771
Name: Channel Cndtn Rtg, dtype: int64

Culvert Cndtn Rtg
False    25771
Name: Culvert Cndtn Rtg, dtype: int64

Method Rtg
False    25771
Name: Method Rtg, dtype: int64

Operating Rtg
False    25771
Name: Operating Rtg, dtype: int64

Invntry Rtg
False    25771
Name: Invntry Rtg, dtype: int64

Str Eval
False    25771
Name: Str Eval, dtype: int64

Deck Geom
False    25771
Name: Deck Geom, dtype: int64

UndClr, Ver, Hor
False    25771
Name: UndClr, Ver, Hor, dtype: int64

Br Pstng
False    25771
Name: Br Pstng, dtype: int64

WatWy Adequcy
False    25771
Name: WatWy Adequcy, dtype: int64

App Rdwy Align
False    25771
Name: App Rdwy Align, dtype: int64

Type of Work
False    25771
Name: Type of Work, dtype: int64

Len Str Imprvmnt
False    25771
Name: Len Str Imprvmnt, dtype: int64

Inspection Date
False    25771
Name: Inspection Date, dtype: int64

Insp Freq (mths)
False    25771
Name: Insp Freq (mths), dtype: int64

Crtcl Feat Insp
False    25771
Name: Crtcl Feat Insp, dtype: int64

Crtcl Feat Insp Date
False    25771
Name: Crtcl Feat Insp Date, dtype: int64

Br Impvmt $
False    25771
Name: Br Impvmt $, dtype: int64

Rdwy Impvmt $
False    25771
Name: Rdwy Impvmt $, dtype: int64

Total Proj $
False    25771
Name: Total Proj $, dtype: int64

Yr of Impvmt $ Estmt
False    25771
Name: Yr of Impvmt $ Estmt, dtype: int64

Yr Rcnstrctd
False    25771
Name: Yr Rcnstrctd, dtype: int64

Deck Type
False    25771
Name: Deck Type, dtype: int64

ADTT
False    25771
Name: ADTT, dtype: int64

NBIS Br Len
False    25771
Name: NBIS Br Len, dtype: int64

Scour Crtcl Br
False    25771
Name: Scour Crtcl Br, dtype: int64

Future ADT
False    25771
Name: Future ADT, dtype: int64

Yr of Future ADT
False    25771
Name: Yr of Future ADT, dtype: int64

Bridge Cndn CAT10
False    25771
Name: Bridge Cndn CAT10, dtype: int64

Ovreall Bridge Cndn CAT23
False    25771
Name: Ovreall Bridge Cndn CAT23, dtype: int64

In [6]:
missing_na = df.isna()

for column in missing_na.columns.values.tolist():
    print(column)
    print (missing_na[column].value_counts())
    print("")

State ID
False    25771
Name: State ID, dtype: int64

Structure #
False    25771
Name: Structure #, dtype: int64

Inventory Route
False    25771
Name: Inventory Route, dtype: int64

HwyAgency District
False    25771
Name: HwyAgency District, dtype: int64

County Code
False    25771
Name: County Code, dtype: int64

Place Code
False    25771
Name: Place Code, dtype: int64

Feature Int
False    25771
Name: Feature Int, dtype: int64

Facility Carried by Str.
False    25771
Name: Facility Carried by Str., dtype: int64

Location
False    25771
Name: Location, dtype: int64

Min. Vert. Clearance
False    25771
Name: Min. Vert. Clearance, dtype: int64

KM Point
False    25771
Name: KM Point, dtype: int64

Base HWY Ntwrk
False    25771
Name: Base HWY Ntwrk, dtype: int64

SubRte #
False    25771
Name: SubRte #, dtype: int64

Lat (DD-MM-SS.ss)
False    25771
Name: Lat (DD-MM-SS.ss), dtype: int64

Long (DDD-MM-SS.ss)
False    25771
Name: Long (DDD-MM-SS.ss), dtype: int64

DTR Len
False    25771
Name: DTR Len, dtype: int64

Toll
False    25771
Name: Toll, dtype: int64

Maint. Resp.
False    25771
Name: Maint. Resp., dtype: int64

Owner
False    25771
Name: Owner, dtype: int64

Func Class
False    25771
Name: Func Class, dtype: int64

Year Built
False    25771
Name: Year Built, dtype: int64

Lanes On Str.
False    25771
Name: Lanes On Str., dtype: int64

Lanes Under Str.
False    25771
Name: Lanes Under Str., dtype: int64

ADT
False    25771
Name: ADT, dtype: int64

Year of ADT
False    25771
Name: Year of ADT, dtype: int64

Design Load
False    25771
Name: Design Load, dtype: int64

App. Rdwy Width
False    25771
Name: App. Rdwy Width, dtype: int64

Br. Median
False    25771
Name: Br. Median, dtype: int64

Skew
False    25771
Name: Skew, dtype: int64

Flared
False    25771
Name: Flared, dtype: int64

Tr Sfty Feat
False    25771
Name: Tr Sfty Feat, dtype: int64

Hist. Value
False    25771
Name: Hist. Value, dtype: int64

Navi Ctrl
False    25771
Name: Navi Ctrl, dtype: int64

Navi Ver Clr
False    25771
Name: Navi Ver Clr, dtype: int64

Navi Hor Clr
False    25771
Name: Navi Hor Clr, dtype: int64

Str Opn/ Pstd/ Clsd
False    25771
Name: Str Opn/ Pstd/ Clsd, dtype: int64

Type of Srvc
False    25771
Name: Type of Srvc, dtype: int64

Str Type
False    25771
Name: Str Type, dtype: int64

Str Type App Spans
False    25771
Name: Str Type App Spans, dtype: int64

Span # in Main Unit
False    25771
Name: Span # in Main Unit, dtype: int64

App Span #
False    25771
Name: App Span #, dtype: int64

Max Span Len
False    25771
Name: Max Span Len, dtype: int64

Str Len (m)
False    25771
Name: Str Len (m), dtype: int64

Rdwy Width (m)
False    25771
Name: Rdwy Width (m), dtype: int64

Deck Width (m)
False    25771
Name: Deck Width (m), dtype: int64

Deck Cndtn Rtg
False    25771
Name: Deck Cndtn Rtg, dtype: int64

Super Cndtn Rtg
False    25771
Name: Super Cndtn Rtg, dtype: int64

Sub Cndtn Rtg
False    25771
Name: Sub Cndtn Rtg, dtype: int64

Channel Cndtn Rtg
False    25771
Name: Channel Cndtn Rtg, dtype: int64

Culvert Cndtn Rtg
False    25771
Name: Culvert Cndtn Rtg, dtype: int64

Method Rtg
False    25771
Name: Method Rtg, dtype: int64

Operating Rtg
False    25771
Name: Operating Rtg, dtype: int64

Invntry Rtg
False    25771
Name: Invntry Rtg, dtype: int64

Str Eval
False    25771
Name: Str Eval, dtype: int64

Deck Geom
False    25771
Name: Deck Geom, dtype: int64

UndClr, Ver, Hor
False    25771
Name: UndClr, Ver, Hor, dtype: int64

Br Pstng
False    25771
Name: Br Pstng, dtype: int64

WatWy Adequcy
False    25771
Name: WatWy Adequcy, dtype: int64

App Rdwy Align
False    25771
Name: App Rdwy Align, dtype: int64

Type of Work
False    25771
Name: Type of Work, dtype: int64

Len Str Imprvmnt
False    25771
Name: Len Str Imprvmnt, dtype: int64

Inspection Date
False    25771
Name: Inspection Date, dtype: int64

Insp Freq (mths)
False    25771
Name: Insp Freq (mths), dtype: int64

Crtcl Feat Insp
False    25771
Name: Crtcl Feat Insp, dtype: int64

Crtcl Feat Insp Date
False    25771
Name: Crtcl Feat Insp Date, dtype: int64

Br Impvmt $
False    25771
Name: Br Impvmt $, dtype: int64

Rdwy Impvmt $
False    25771
Name: Rdwy Impvmt $, dtype: int64

Total Proj $
False    25771
Name: Total Proj $, dtype: int64

Yr of Impvmt $ Estmt
False    25771
Name: Yr of Impvmt $ Estmt, dtype: int64

Yr Rcnstrctd
False    25771
Name: Yr Rcnstrctd, dtype: int64

Deck Type
False    25771
Name: Deck Type, dtype: int64

ADTT
False    25771
Name: ADTT, dtype: int64

NBIS Br Len
False    25771
Name: NBIS Br Len, dtype: int64

Scour Crtcl Br
False    25771
Name: Scour Crtcl Br, dtype: int64

Future ADT
False    25771
Name: Future ADT, dtype: int64

Yr of Future ADT
False    25771
Name: Yr of Future ADT, dtype: int64

Bridge Cndn CAT10
False    25771
Name: Bridge Cndn CAT10, dtype: int64

Ovreall Bridge Cndn CAT23
False    25771
Name: Ovreall Bridge Cndn CAT23, dtype: int64

### 2.4 Correcting Data Types:

In [7]:
print(df.dtypes)

State ID                     object
Structure #                  object
Inventory Route              object
HwyAgency District           object
County Code                  object
                              ...
Scour Crtcl Br               object
Future ADT                   object
Yr of Future ADT             object
Bridge Cndn CAT10            object
Ovreall Bridge Cndn CAT23    object
Length: 78, dtype: object

In [8]:
df = df.apply(pd.to_numeric, errors='ignore')

df.dtypes

State ID                       int64
Structure #                   object
Inventory Route               object
HwyAgency District             int64
County Code                    int64
                              ...
Scour Crtcl Br                object
Future ADT                   float64
Yr of Future ADT             float64
Bridge Cndn CAT10             object
Ovreall Bridge Cndn CAT23    float64
Length: 78, dtype: object

### 2.5 Data Standardization:

The National Bridge Inventory (NBI) database codified most of the columns (e.g. latitude, longitude, functional classification, etc.). This section includes standardizing a few of these columns required for our analyses. 

#### 2.5.1 Latitude:

Latitude column (i.e. "Lat (DD-MM-SS.ss)") includes values of 8-digit consective format without separation, comma, or deg/min/sec designation. As the column header shows, the first 2 digits from left indicate degrees, the 3rd and 4th digits indicate minutes, 5th and 6th digits show seconds, and the last 7th and 8th digits indicate decimals of the seconds. 

For bridges on STRAHNET and STRAHNET Connector highways and on the NHS, record and code the latitude of each in degrees, minutes and seconds to the nearest hundredth of a second (with an assumed decimal point). The point of the coordinate may be the beginning of the bridge in the direction of the inventory or any other consistent point of reference on the bridge which is compatible with the LRS. If the bridge is not on a STRAHNET highway or the NHS, a code of all zeros is acceptable, but it is preferable to code the latitude if available.

The reason for the increased precision is to facilitate the use of Global Positioning System (GPS) data directly into this item. The increased precision is not currently mandatory and, if GPS readings are not available, the current measuring methods and level of precision may continue to be used. The minimum precision should be to the nearest minute, but the preferred precision is to the nearest hundredth of a second using GPS methods.

**EXAMPLE: Latitude is 35Â°27.3' \--- (current precision) 35271800 \--- (acceptable coding) 35270000 \--- 35Â°27'18.55"   (GPS reading) 35271855**

In [46]:

#----------------------- Fixing Latitudes---------------------------------------
df['lat_dd'] = df['Lat (DD-MM-SS.ss)'] // 1000000
df['lat_ddr'] = df['Lat (DD-MM-SS.ss)'] % 1000000 # right side digits remaining
df['lat_mm'] = df['lat_ddr'] // 10000
df['lat_mmr'] = df['lat_ddr'] % 10000 # right side digits remaining
df['lat_ss.ss'] = df['lat_mmr'] / 100
df['lat_deg'] = df['lat_dd']+(df['lat_mm']/60)+(df['lat_ss.ss']/3600)

#----------------------- Fixing Longitudes---------------------------------------
df['long_dd'] = df['Long (DDD-MM-SS.ss)'] // 1000000
df['long_ddr'] = df['Long (DDD-MM-SS.ss)'] % 1000000 # right side digits remaining
df['long_mm'] = df['long_ddr'] // 10000
df['long_mmr'] = df['long_ddr'] % 10000 # right side digits remaining
df['long_ss.ss'] = df['long_mmr'] / 100
df['long_deg'] = (df['long_dd']+(df['long_mm']/60)+(df['long_ss.ss']/3600))*(-1)

df.dropna(inplace=True)
df.dropna(how = 'all')
df.dropna(subset=['lat_deg'])

df[['Lat (DD-MM-SS.ss)', 'lat_dd', 'lat_mm', 'lat_ss.ss','lat_deg','Long (DDD-MM-SS.ss)', 'long_dd', 'long_mm', 'long_ss.ss','long_deg']].head(100)

,Lat (DD-MM-SS.ss),lat_dd,lat_mm,lat_ss.ss,lat_deg,Long (DDD-MM-SS.ss),long_dd,long_mm,long_ss.ss,long_deg
0,40454199.0,40.0,45.0,41.99,40.761664,122197000.0,122.0,19.0,70.00,-122.336111
1,39000000.0,39.0,0.0,0.00,39.000000,120562375.0,120.0,56.0,23.75,-120.939931
2,34060810.0,34.0,6.0,8.10,34.102250,119061488.0,119.0,6.0,14.88,-119.104133
3,32433594.0,32.0,43.0,35.94,32.726650,117084854.0,117.0,8.0,48.54,-117.146817
4,34065929.0,34.0,6.0,59.29,34.116469,119054787.0,119.0,5.0,47.87,-119.096631
...,...,...,...,...,...,...,...,...,...,...
99,41481170.0,41.0,48.0,11.70,41.803250,124085547.0,124.0,8.0,55.47,-124.148742
100,41463882.0,41.0,46.0,38.82,41.777450,124105700.0,124.0,10.0,57.00,-124.182500
101,41462217.0,41.0,46.0,22.17,41.772825,124111295.0,124.0,11.0,12.95,-124.186931
102,41504924.0,41.0,50.0,49.24,41.847011,123545455.0,123.0,54.0,54.55,-123.915153
103,41510705.0,41.0,51.0,7.05,41.851958,123540635.0,123.0,54.0,6.35,-123.901764

In [ ]:
deterioration = df[['Year Built', 'Ovreall Bridge Cndn CAT23']]

deterioration.to_csv("deterioration.csv", index=False)

deterioration

In [ ]:
deterioration.dtypes

In [ ]:
#deterioration[["Year Built", "Overall Bridge Cndn CAT23"]].describe()

deterioration = deterioration.apply(pd.to_numeric, errors='ignore')

In [ ]:
deterioration['Year Built'].astype('int64', errors='ignore')
deterioration.infer_objects()

In [ ]:
deterioration.dtypes

### 2.5 Exploring Data (Bridge Deterioration vs. Year Built):

In [ ]:
avg_bore=deterioration['Year Built'].astype('float').mean(axis=0)
print("Average of bore:", avg_bore)

In [ ]:
avg_cndn=deterioration['Ovreall Bridge Cndn CAT23'].astype('float').mean(axis=0)
print("Average of cndn:", avg_cndn)